// <auto-generated />
using BC.SchoolRegistrationApp.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BC.SchoolRegistrationApp.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250624120041_StudentTableUpdated")]
    partial class StudentTableUpdated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Class", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("ID");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "9A"
                        },
                        new
                        {
                            ID = 2,
                            Name = "9B"
                        },
                        new
                        {
                            ID = 3,
                            Name = "9C"
                        },
                        new
                        {
                            ID = 4,
                            Name = "10A"
                        },
                        new
                        {
                            ID = 5,
                            Name = "10B"
                        },
                        new
                        {
                            ID = 6,
                            Name = "10C"
                        },
                        new
                        {
                            ID = 7,
                            Name = "11A"
                        },
                        new
                        {
                            ID = 8,
                            Name = "11B"
                        },
                        new
                        {
                            ID = 9,
                            Name = "11C"
                        },
                        new
                        {
                            ID = 10,
                            Name = "12A"
                        },
                        new
                        {
                            ID = 11,
                            Name = "12B"
                        },
                        new
                        {
                            ID = 12,
                            Name = "12C"
                        });
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.ClassLesson", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClassID");

                    b.HasIndex("LessonID");

                    b.HasIndex("TeacherID");

                    b.ToTable("ClassLessons");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Exam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ExamType")
                        .HasColumnType("int");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LessonID");

                    b.ToTable("Exam");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ExamType = 1,
                            LessonID = 1
                        },
                        new
                        {
                            ID = 2,
                            ExamType = 2,
                            LessonID = 1
                        },
                        new
                        {
                            ID = 3,
                            ExamType = 3,
                            LessonID = 1
                        },
                        new
                        {
                            ID = 4,
                            ExamType = 1,
                            LessonID = 2
                        },
                        new
                        {
                            ID = 5,
                            ExamType = 2,
                            LessonID = 2
                        },
                        new
                        {
                            ID = 6,
                            ExamType = 3,
                            LessonID = 2
                        },
                        new
                        {
                            ID = 7,
                            ExamType = 1,
                            LessonID = 3
                        },
                        new
                        {
                            ID = 8,
                            ExamType = 2,
                            LessonID = 3
                        },
                        new
                        {
                            ID = 9,
                            ExamType = 3,
                            LessonID = 3
                        },
                        new
                        {
                            ID = 10,
                            ExamType = 1,
                            LessonID = 4
                        },
                        new
                        {
                            ID = 11,
                            ExamType = 2,
                            LessonID = 4
                        },
                        new
                        {
                            ID = 12,
                            ExamType = 3,
                            LessonID = 4
                        },
                        new
                        {
                            ID = 13,
                            ExamType = 1,
                            LessonID = 5
                        },
                        new
                        {
                            ID = 14,
                            ExamType = 2,
                            LessonID = 5
                        },
                        new
                        {
                            ID = 15,
                            ExamType = 3,
                            LessonID = 5
                        },
                        new
                        {
                            ID = 16,
                            ExamType = 1,
                            LessonID = 6
                        },
                        new
                        {
                            ID = 17,
                            ExamType = 2,
                            LessonID = 6
                        },
                        new
                        {
                            ID = 18,
                            ExamType = 3,
                            LessonID = 6
                        },
                        new
                        {
                            ID = 19,
                            ExamType = 1,
                            LessonID = 7
                        },
                        new
                        {
                            ID = 20,
                            ExamType = 2,
                            LessonID = 7
                        },
                        new
                        {
                            ID = 21,
                            ExamType = 3,
                            LessonID = 7
                        },
                        new
                        {
                            ID = 22,
                            ExamType = 1,
                            LessonID = 8
                        },
                        new
                        {
                            ID = 23,
                            ExamType = 2,
                            LessonID = 8
                        },
                        new
                        {
                            ID = 24,
                            ExamType = 3,
                            LessonID = 8
                        },
                        new
                        {
                            ID = 25,
                            ExamType = 1,
                            LessonID = 9
                        },
                        new
                        {
                            ID = 26,
                            ExamType = 2,
                            LessonID = 9
                        },
                        new
                        {
                            ID = 27,
                            ExamType = 3,
                            LessonID = 9
                        },
                        new
                        {
                            ID = 28,
                            ExamType = 1,
                            LessonID = 10
                        },
                        new
                        {
                            ID = 29,
                            ExamType = 2,
                            LessonID = 10
                        },
                        new
                        {
                            ID = 30,
                            ExamType = 3,
                            LessonID = 10
                        },
                        new
                        {
                            ID = 31,
                            ExamType = 1,
                            LessonID = 11
                        },
                        new
                        {
                            ID = 32,
                            ExamType = 2,
                            LessonID = 11
                        },
                        new
                        {
                            ID = 33,
                            ExamType = 3,
                            LessonID = 11
                        },
                        new
                        {
                            ID = 34,
                            ExamType = 1,
                            LessonID = 12
                        },
                        new
                        {
                            ID = 35,
                            ExamType = 2,
                            LessonID = 12
                        },
                        new
                        {
                            ID = 36,
                            ExamType = 3,
                            LessonID = 12
                        },
                        new
                        {
                            ID = 37,
                            ExamType = 1,
                            LessonID = 13
                        },
                        new
                        {
                            ID = 38,
                            ExamType = 2,
                            LessonID = 13
                        },
                        new
                        {
                            ID = 39,
                            ExamType = 3,
                            LessonID = 13
                        });
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Grade", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ExamID");

                    b.HasIndex("LessonID");

                    b.HasIndex("StudentID");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Lesson", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeeklyHour")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "English",
                            WeeklyHour = 4
                        },
                        new
                        {
                            ID = 2,
                            Name = "Turkish",
                            WeeklyHour = 5
                        },
                        new
                        {
                            ID = 3,
                            Name = "Mathematics",
                            WeeklyHour = 6
                        },
                        new
                        {
                            ID = 4,
                            Name = "Physics",
                            WeeklyHour = 4
                        },
                        new
                        {
                            ID = 5,
                            Name = "Chemistry",
                            WeeklyHour = 2
                        },
                        new
                        {
                            ID = 6,
                            Name = "Biology",
                            WeeklyHour = 2
                        },
                        new
                        {
                            ID = 7,
                            Name = "History",
                            WeeklyHour = 2
                        },
                        new
                        {
                            ID = 8,
                            Name = "Geography",
                            WeeklyHour = 2
                        },
                        new
                        {
                            ID = 9,
                            Name = "Religious Culture and Moral Knowledge",
                            WeeklyHour = 1
                        },
                        new
                        {
                            ID = 10,
                            Name = "Physical Education and Sports",
                            WeeklyHour = 2
                        },
                        new
                        {
                            ID = 11,
                            Name = "Visual Arts / Music",
                            WeeklyHour = 2
                        },
                        new
                        {
                            ID = 12,
                            Name = "Health Knowledge and Traffic Culture",
                            WeeklyHour = 1
                        },
                        new
                        {
                            ID = 13,
                            Name = "German",
                            WeeklyHour = 3
                        });
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.LessonSchedule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClassLessonID")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("LessonHour")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClassLessonID");

                    b.ToTable("LessonSchedules");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ClassID")
                        .HasColumnType("int");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Photograph")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("ClassID");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ClassID = 1,
                            IsPassed = false,
                            Name = "Elif",
                            Number = "1001",
                            Photograph = "",
                            Surname = "Yılmaz"
                        },
                        new
                        {
                            ID = 2,
                            ClassID = 1,
                            IsPassed = false,
                            Name = "Ahmet",
                            Number = "1002",
                            Photograph = "",
                            Surname = "Demir"
                        },
                        new
                        {
                            ID = 3,
                            ClassID = 1,
                            IsPassed = false,
                            Name = "Zeynep",
                            Number = "1003",
                            Photograph = "",
                            Surname = "Kaya"
                        },
                        new
                        {
                            ID = 4,
                            ClassID = 1,
                            IsPassed = false,
                            Name = "Mehmet",
                            Number = "1004",
                            Photograph = "",
                            Surname = "Aydın"
                        },
                        new
                        {
                            ID = 5,
                            ClassID = 1,
                            IsPassed = false,
                            Name = "Ayşe",
                            Number = "1005",
                            Photograph = "",
                            Surname = "Şahin"
                        },
                        new
                        {
                            ID = 6,
                            ClassID = 2,
                            IsPassed = false,
                            Name = "Ece",
                            Number = "2001",
                            Photograph = "",
                            Surname = "Koç"
                        },
                        new
                        {
                            ID = 7,
                            ClassID = 2,
                            IsPassed = false,
                            Name = "Yusuf",
                            Number = "2002",
                            Photograph = "",
                            Surname = "Arslan"
                        },
                        new
                        {
                            ID = 8,
                            ClassID = 2,
                            IsPassed = false,
                            Name = "Naz",
                            Number = "2003",
                            Photograph = "",
                            Surname = "Çelik"
                        },
                        new
                        {
                            ID = 9,
                            ClassID = 2,
                            IsPassed = false,
                            Name = "Emre",
                            Number = "2004",
                            Photograph = "",
                            Surname = "Bozkurt"
                        },
                        new
                        {
                            ID = 10,
                            ClassID = 2,
                            IsPassed = false,
                            Name = "Melis",
                            Number = "2005",
                            Photograph = "",
                            Surname = "Türkmen"
                        },
                        new
                        {
                            ID = 11,
                            ClassID = 3,
                            IsPassed = false,
                            Name = "Burak",
                            Number = "3001",
                            Photograph = "",
                            Surname = "Öztürk"
                        },
                        new
                        {
                            ID = 12,
                            ClassID = 3,
                            IsPassed = false,
                            Name = "Ceren",
                            Number = "3002",
                            Photograph = "",
                            Surname = "Yıldız"
                        },
                        new
                        {
                            ID = 13,
                            ClassID = 3,
                            IsPassed = false,
                            Name = "Okan",
                            Number = "3003",
                            Photograph = "",
                            Surname = "Kurt"
                        },
                        new
                        {
                            ID = 14,
                            ClassID = 3,
                            IsPassed = false,
                            Name = "Nisa",
                            Number = "3004",
                            Photograph = "",
                            Surname = "Bal"
                        },
                        new
                        {
                            ID = 15,
                            ClassID = 3,
                            IsPassed = false,
                            Name = "Selim",
                            Number = "3005",
                            Photograph = "",
                            Surname = "Er"
                        },
                        new
                        {
                            ID = 16,
                            ClassID = 4,
                            IsPassed = false,
                            Name = "İrem",
                            Number = "4001",
                            Photograph = "",
                            Surname = "Aksoy"
                        },
                        new
                        {
                            ID = 17,
                            ClassID = 4,
                            IsPassed = false,
                            Name = "Berat",
                            Number = "4002",
                            Photograph = "",
                            Surname = "Aslan"
                        },
                        new
                        {
                            ID = 18,
                            ClassID = 4,
                            IsPassed = false,
                            Name = "Deniz",
                            Number = "4003",
                            Photograph = "",
                            Surname = "Taş"
                        },
                        new
                        {
                            ID = 19,
                            ClassID = 4,
                            IsPassed = false,
                            Name = "Esra",
                            Number = "4004",
                            Photograph = "",
                            Surname = "Yalçın"
                        },
                        new
                        {
                            ID = 20,
                            ClassID = 4,
                            IsPassed = false,
                            Name = "Hakan",
                            Number = "4005",
                            Photograph = "",
                            Surname = "Eren"
                        },
                        new
                        {
                            ID = 21,
                            ClassID = 5,
                            IsPassed = false,
                            Name = "Alper",
                            Number = "5001",
                            Photograph = "",
                            Surname = "Şimşek"
                        },
                        new
                        {
                            ID = 22,
                            ClassID = 5,
                            IsPassed = false,
                            Name = "Derya",
                            Number = "5002",
                            Photograph = "",
                            Surname = "Özkan"
                        },
                        new
                        {
                            ID = 23,
                            ClassID = 5,
                            IsPassed = false,
                            Name = "Efe",
                            Number = "5003",
                            Photograph = "",
                            Surname = "Çakır"
                        },
                        new
                        {
                            ID = 24,
                            ClassID = 5,
                            IsPassed = false,
                            Name = "Seda",
                            Number = "5004",
                            Photograph = "",
                            Surname = "Güneş"
                        },
                        new
                        {
                            ID = 25,
                            ClassID = 5,
                            IsPassed = false,
                            Name = "Bora",
                            Number = "5005",
                            Photograph = "",
                            Surname = "Kurtuluş"
                        },
                        new
                        {
                            ID = 26,
                            ClassID = 6,
                            IsPassed = false,
                            Name = "Mert",
                            Number = "6001",
                            Photograph = "",
                            Surname = "Kaplan"
                        },
                        new
                        {
                            ID = 27,
                            ClassID = 6,
                            IsPassed = false,
                            Name = "Gizem",
                            Number = "6002",
                            Photograph = "",
                            Surname = "Durmaz"
                        },
                        new
                        {
                            ID = 28,
                            ClassID = 6,
                            IsPassed = false,
                            Name = "Umut",
                            Number = "6003",
                            Photograph = "",
                            Surname = "Tan"
                        },
                        new
                        {
                            ID = 29,
                            ClassID = 6,
                            IsPassed = false,
                            Name = "Yaren",
                            Number = "6004",
                            Photograph = "",
                            Surname = "Özdemir"
                        },
                        new
                        {
                            ID = 30,
                            ClassID = 6,
                            IsPassed = false,
                            Name = "Kerem",
                            Number = "6005",
                            Photograph = "",
                            Surname = "Boz"
                        },
                        new
                        {
                            ID = 31,
                            ClassID = 7,
                            IsPassed = false,
                            Name = "İlayda",
                            Number = "7001",
                            Photograph = "",
                            Surname = "Sezer"
                        },
                        new
                        {
                            ID = 32,
                            ClassID = 7,
                            IsPassed = false,
                            Name = "Tunahan",
                            Number = "7002",
                            Photograph = "",
                            Surname = "Kurt"
                        },
                        new
                        {
                            ID = 33,
                            ClassID = 7,
                            IsPassed = false,
                            Name = "Melike",
                            Number = "7003",
                            Photograph = "",
                            Surname = "Avcı"
                        },
                        new
                        {
                            ID = 34,
                            ClassID = 7,
                            IsPassed = false,
                            Name = "Harun",
                            Number = "7004",
                            Photograph = "",
                            Surname = "Sönmez"
                        },
                        new
                        {
                            ID = 35,
                            ClassID = 7,
                            IsPassed = false,
                            Name = "Büşra",
                            Number = "7005",
                            Photograph = "",
                            Surname = "Erdoğan"
                        },
                        new
                        {
                            ID = 36,
                            ClassID = 8,
                            IsPassed = false,
                            Name = "Fatih",
                            Number = "8001",
                            Photograph = "",
                            Surname = "İnce"
                        },
                        new
                        {
                            ID = 37,
                            ClassID = 8,
                            IsPassed = false,
                            Name = "Dilara",
                            Number = "8002",
                            Photograph = "",
                            Surname = "Koşar"
                        },
                        new
                        {
                            ID = 38,
                            ClassID = 8,
                            IsPassed = false,
                            Name = "Ali",
                            Number = "8003",
                            Photograph = "",
                            Surname = "Çetin"
                        },
                        new
                        {
                            ID = 39,
                            ClassID = 8,
                            IsPassed = false,
                            Name = "Sena",
                            Number = "8004",
                            Photograph = "",
                            Surname = "Kaya"
                        },
                        new
                        {
                            ID = 40,
                            ClassID = 8,
                            IsPassed = false,
                            Name = "Yiğit",
                            Number = "8005",
                            Photograph = "",
                            Surname = "Acar"
                        },
                        new
                        {
                            ID = 41,
                            ClassID = 9,
                            IsPassed = false,
                            Name = "Zeliha",
                            Number = "9001",
                            Photograph = "",
                            Surname = "Doğan"
                        },
                        new
                        {
                            ID = 42,
                            ClassID = 9,
                            IsPassed = false,
                            Name = "Can",
                            Number = "9002",
                            Photograph = "",
                            Surname = "Yıldırım"
                        },
                        new
                        {
                            ID = 43,
                            ClassID = 9,
                            IsPassed = false,
                            Name = "Rabia",
                            Number = "9003",
                            Photograph = "",
                            Surname = "Er"
                        },
                        new
                        {
                            ID = 44,
                            ClassID = 9,
                            IsPassed = false,
                            Name = "Taha",
                            Number = "9004",
                            Photograph = "",
                            Surname = "Gür"
                        },
                        new
                        {
                            ID = 45,
                            ClassID = 9,
                            IsPassed = false,
                            Name = "Simay",
                            Number = "9005",
                            Photograph = "",
                            Surname = "Polat"
                        },
                        new
                        {
                            ID = 46,
                            ClassID = 10,
                            IsPassed = false,
                            Name = "Furkan",
                            Number = "10001",
                            Photograph = "",
                            Surname = "Kılıç"
                        },
                        new
                        {
                            ID = 47,
                            ClassID = 10,
                            IsPassed = false,
                            Name = "Beyza",
                            Number = "10002",
                            Photograph = "",
                            Surname = "Sarı"
                        },
                        new
                        {
                            ID = 48,
                            ClassID = 10,
                            IsPassed = false,
                            Name = "Talha",
                            Number = "10003",
                            Photograph = "",
                            Surname = "Özer"
                        },
                        new
                        {
                            ID = 49,
                            ClassID = 10,
                            IsPassed = false,
                            Name = "Gül",
                            Number = "10004",
                            Photograph = "",
                            Surname = "Toprak"
                        },
                        new
                        {
                            ID = 50,
                            ClassID = 10,
                            IsPassed = false,
                            Name = "Ozan",
                            Number = "10005",
                            Photograph = "",
                            Surname = "Güneş"
                        },
                        new
                        {
                            ID = 51,
                            ClassID = 11,
                            IsPassed = false,
                            Name = "Selin",
                            Number = "11001",
                            Photograph = "",
                            Surname = "Yavuz"
                        },
                        new
                        {
                            ID = 52,
                            ClassID = 11,
                            IsPassed = false,
                            Name = "Baran",
                            Number = "11002",
                            Photograph = "",
                            Surname = "Yüce"
                        },
                        new
                        {
                            ID = 53,
                            ClassID = 11,
                            IsPassed = false,
                            Name = "Cansu",
                            Number = "11003",
                            Photograph = "",
                            Surname = "Ergin"
                        },
                        new
                        {
                            ID = 54,
                            ClassID = 11,
                            IsPassed = false,
                            Name = "Onur",
                            Number = "11004",
                            Photograph = "",
                            Surname = "Aydın"
                        },
                        new
                        {
                            ID = 55,
                            ClassID = 11,
                            IsPassed = false,
                            Name = "Nehir",
                            Number = "11005",
                            Photograph = "",
                            Surname = "Deniz"
                        },
                        new
                        {
                            ID = 56,
                            ClassID = 12,
                            IsPassed = false,
                            Name = "Serhat",
                            Number = "12001",
                            Photograph = "",
                            Surname = "Çınar"
                        },
                        new
                        {
                            ID = 57,
                            ClassID = 12,
                            IsPassed = false,
                            Name = "Nazlı",
                            Number = "12002",
                            Photograph = "",
                            Surname = "Taşdemir"
                        },
                        new
                        {
                            ID = 58,
                            ClassID = 12,
                            IsPassed = false,
                            Name = "Arda",
                            Number = "12003",
                            Photograph = "",
                            Surname = "Ersoy"
                        },
                        new
                        {
                            ID = 59,
                            ClassID = 12,
                            IsPassed = false,
                            Name = "İdil",
                            Number = "12004",
                            Photograph = "",
                            Surname = "Yücel"
                        },
                        new
                        {
                            ID = 60,
                            ClassID = 12,
                            IsPassed = false,
                            Name = "Melek",
                            Number = "12005",
                            Photograph = "",
                            Surname = "Güler"
                        });
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Teacher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LessonID");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            LessonID = 1,
                            Name = "Alice",
                            Surname = "Johnson"
                        },
                        new
                        {
                            ID = 2,
                            LessonID = 1,
                            Name = "David",
                            Surname = "Smith"
                        },
                        new
                        {
                            ID = 3,
                            LessonID = 1,
                            Name = "Can",
                            Surname = "Aslan"
                        },
                        new
                        {
                            ID = 4,
                            LessonID = 2,
                            Name = "Merve",
                            Surname = "Yılmaz"
                        },
                        new
                        {
                            ID = 5,
                            LessonID = 2,
                            Name = "Ahmet",
                            Surname = "Kara"
                        },
                        new
                        {
                            ID = 6,
                            LessonID = 2,
                            Name = "Elif",
                            Surname = "Aydın"
                        },
                        new
                        {
                            ID = 7,
                            LessonID = 3,
                            Name = "John",
                            Surname = "Doe"
                        },
                        new
                        {
                            ID = 8,
                            LessonID = 3,
                            Name = "Ayşe",
                            Surname = "Çelik"
                        },
                        new
                        {
                            ID = 9,
                            LessonID = 3,
                            Name = "Mehmet",
                            Surname = "Kurt"
                        },
                        new
                        {
                            ID = 10,
                            LessonID = 3,
                            Name = "Fatma",
                            Surname = "Demir"
                        },
                        new
                        {
                            ID = 11,
                            LessonID = 3,
                            Name = "Dilan",
                            Surname = "Kaya"
                        },
                        new
                        {
                            ID = 12,
                            LessonID = 4,
                            Name = "Selin",
                            Surname = "Aksoy"
                        },
                        new
                        {
                            ID = 13,
                            LessonID = 4,
                            Name = "Kemal",
                            Surname = "Öz"
                        },
                        new
                        {
                            ID = 14,
                            LessonID = 5,
                            Name = "Burcu",
                            Surname = "Güneş"
                        },
                        new
                        {
                            ID = 15,
                            LessonID = 5,
                            Name = "Tuncay",
                            Surname = "Işık"
                        },
                        new
                        {
                            ID = 16,
                            LessonID = 6,
                            Name = "Melisa",
                            Surname = "Ersoy"
                        },
                        new
                        {
                            ID = 17,
                            LessonID = 6,
                            Name = "Levent",
                            Surname = "Koç"
                        },
                        new
                        {
                            ID = 18,
                            LessonID = 7,
                            Name = "Zeynep",
                            Surname = "Polat"
                        },
                        new
                        {
                            ID = 19,
                            LessonID = 7,
                            Name = "Barış",
                            Surname = "Can"
                        },
                        new
                        {
                            ID = 20,
                            LessonID = 8,
                            Name = "Sibel",
                            Surname = "Yıldırım"
                        },
                        new
                        {
                            ID = 21,
                            LessonID = 8,
                            Name = "Okan",
                            Surname = "Şahin"
                        },
                        new
                        {
                            ID = 22,
                            LessonID = 9,
                            Name = "Hasan",
                            Surname = "Yüce"
                        },
                        new
                        {
                            ID = 23,
                            LessonID = 10,
                            Name = "Emre",
                            Surname = "Kaplan"
                        },
                        new
                        {
                            ID = 24,
                            LessonID = 10,
                            Name = "Buse",
                            Surname = "Türkmen"
                        },
                        new
                        {
                            ID = 25,
                            LessonID = 11,
                            Name = "İlknur",
                            Surname = "Balcı"
                        },
                        new
                        {
                            ID = 26,
                            LessonID = 12,
                            Name = "Gökhan",
                            Surname = "Sezer"
                        },
                        new
                        {
                            ID = 27,
                            LessonID = 13,
                            Name = "Stefan",
                            Surname = "Müller"
                        },
                        new
                        {
                            ID = 28,
                            LessonID = 13,
                            Name = "Lena",
                            Surname = "Schmidt"
                        });
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.ClassLesson", b =>
                {
                    b.HasOne("BC.SchoolRegistrationApp.Entity.Entities.Class", "Class")
                        .WithMany("ClassLessons")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BC.SchoolRegistrationApp.Entity.Entities.Lesson", "Lesson")
                        .WithMany("ClassLessons")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC.SchoolRegistrationApp.Entity.Entities.Teacher", "Teacher")
                        .WithMany("ClassLessons")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Lesson");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Exam", b =>
                {
                    b.HasOne("BC.SchoolRegistrationApp.Entity.Entities.Lesson", "Lesson")
                        .WithMany("Exams")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Grade", b =>
                {
                    b.HasOne("BC.SchoolRegistrationApp.Entity.Entities.Exam", "Exam")
                        .WithMany("Grades")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC.SchoolRegistrationApp.Entity.Entities.Lesson", "Lesson")
                        .WithMany("Grades")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BC.SchoolRegistrationApp.Entity.Entities.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.LessonSchedule", b =>
                {
                    b.HasOne("BC.SchoolRegistrationApp.Entity.Entities.ClassLesson", "ClassLesson")
                        .WithMany("LessonSchedules")
                        .HasForeignKey("ClassLessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassLesson");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Student", b =>
                {
                    b.HasOne("BC.SchoolRegistrationApp.Entity.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Teacher", b =>
                {
                    b.HasOne("BC.SchoolRegistrationApp.Entity.Entities.Lesson", "Lesson")
                        .WithMany("Teachers")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Class", b =>
                {
                    b.Navigation("ClassLessons");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.ClassLesson", b =>
                {
                    b.Navigation("LessonSchedules");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Exam", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Lesson", b =>
                {
                    b.Navigation("ClassLessons");

                    b.Navigation("Exams");

                    b.Navigation("Grades");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Student", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("BC.SchoolRegistrationApp.Entity.Entities.Teacher", b =>
                {
                    b.Navigation("ClassLessons");
                });
#pragma warning restore 612, 618
        }
    }
}
